nodeLinker: pnp

packageExtensions:
  "@adobe/react-spectrum@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@react-aria/menu@*":
    peerDependencies:
      react-dom: "*"
  "@react-aria/select@*":
    peerDependencies:
      react-dom: "*"
  "@react-aria/tooltip@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/actiongroup@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/breadcrumbs@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/button@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/buttongroup@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/checkbox@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/dialog@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/label@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/listbox@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/menu@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/picker@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/provider@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/radio@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/searchfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/switch@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/tabs@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/textfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/theme-dark@*":
    peerDependencies:
      react: "*"
  "@react-spectrum/theme-default@*":
    peerDependencies:
      react: "*"
  "@react-spectrum/theme-light@*":
    peerDependencies:
      react: "*"
  "@react-spectrum/tooltip@*":
    peerDependencies:
      react-dom: "*"
  "@spectrum-icons/ui@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
      react-dom: "*"
  "@spectrum-icons/workflow@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
      react-dom: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-1.22.10.cjs
