yarnPath: ".yarn/releases/yarn-berry.cjs"

nodeLinker: "pnp"

pnpMode: loose

packageExtensions:
  "@adobe/react-spectrum@3.9.0":
    peerDependencies: 
      react: "*"
      react-dom: "*"
  "@react-aria/menu@3.2.0": 
    peerDependencies:
      react-dom: "*"
  "@react-aria/tooltip@3.1.1":
    peerDependencies: 
      react-dom: "*"
  "@react-spectrum/dialog@3.3.1":
    peerDependencies: 
      react-dom: "*"
  "@react-spectrum/listbox@3.4.1":
    peerDependencies: 
      react-dom: "*"
  "@react-spectrum/menu@3.2.2":
    peerDependencies: 
      react-dom: "*"
  "@react-spectrum/picker@3.2.3":
    peerDependencies: 
      react-dom: "*"
  "@react-spectrum/provider@3.1.3":
    peerDependencies: 
      react-dom: "*"
  "@react-spectrum/theme-dark@3.2.0":
    peerDependencies:
      react: "*"
  "@react-spectrum/theme-default@3.2.0":
    peerDependencies:
      react: "*"
  "@react-spectrum/theme-light@3.1.0":
    peerDependencies:
      react: "*"
  "@react-spectrum/tooltip@3.1.2":
    peerDependencies: 
      react-dom: "*"
  "@spectrum-icons/ui@3.2.0":
    peerDependencies: 
      "@react-spectrum/provider": "*" 
      react-dom: "*"
  "@spectrum-icons/workflow@3.2.0":
    peerDependencies: 
      "@react-spectrum/provider": "*"
      react-dom: "*"
  "@react-spectrum/actiongroup@3.1.2":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/breadcrumbs@3.2.1":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/button@3.4.0":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/checkbox@3.2.2":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/label@3.3.2":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/searchfield@3.1.3":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/switch@3.1.1":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/tabs@3.0.0-beta.0":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/textfield@3.1.5":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/buttongroup@3.2.0":
    peerDependencies:
      react-dom: "*"
  "@react-aria/select@3.3.1": 
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/radio@3.1.2":
    peerDependencies:
      react-dom: "*"