enableInlineBuilds: true

enableTelemetry: false

npmAlwaysAuth: true

npmRegistryServer: "https://artifactory-uw2.adobeitc.com/artifactory/api/npm/npm-local-release"

npmRegistries:
  "https://artifactory-uw2.adobeitc.com/artifactory/api/npm/npm-local-release":
    npmAlwaysAuth: true
    npmAuthToken: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJ0OFkwQkxDWFpNclFURFM4NVgzMUYzSlNhSEFmZlRlV1JaWS1KNWZNcXF3In0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUBhMzY4M2Q4Ny0yZWY1LTRmYjktOTg4OS00NDRkOGI1NDgwNTNcL3VzZXJzXC9oYWxsZW5iZSIsInNjcCI6Im1lbWJlci1vZi1ncm91cHM6KiBhcGk6KiIsImF1ZCI6ImpmLWFydGlmYWN0b3J5QGEzNjgzZDg3LTJlZjUtNGZiOS05ODg5LTQ0NGQ4YjU0ODA1MyIsImlzcyI6ImpmLWFydGlmYWN0b3J5QGEzNjgzZDg3LTJlZjUtNGZiOS05ODg5LTQ0NGQ4YjU0ODA1M1wvdXNlcnNcL2hhbGxlbmJlIiwiaWF0IjoxNjIxNTMwMDQ1LCJqdGkiOiI2NDgwODY0Ni02MjkzLTRhN2EtOGUzNS0zOWZhNTdhNjE4NmYifQ.ROCTZUaSCpSo56YA3wVt1mz2bFPkRvH9ubYpdX147KPtaX3OGMZJwYGj64qXb1Wipmp8p1eQMQAx9e9BZK8_3r28ti5DRgA6lCNyV-izDtmkGf-a5dBBICL1etjhsP1-ixdqMTqBe3l9XaZUm7CUnj0Wn9CLEF-AlKdJf-oFZb6lJQ8otADRbxVS7sh0XTRsrPMV8IkAsfh5n308ux07q7deK7XX_5BMRA78dTtvV9_3x9zyBbJvDxp5nIepGzrskwQtgCvLOnmtHot-kTPwirrLy57ez3ot9cKnbWLdhkDdYG-_4kzQldisKPUY8jb9JWZMZDwP2HPRBpi4P0Bbzw
  "https://artifactory.corp.adobe.com/artifactory/api/npm/npmjs":
    npmAlwaysAuth: true
    npmAuthToken: eyJ2ZXIiOiIyIiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYiLCJraWQiOiJ1cV9pTjBiX2lZZHVRX0JDeklfVklsdWItdUtQa01MY3ZQXzA3NzJnMXd3In0.eyJzdWIiOiJqZi1hcnRpZmFjdG9yeUAyZWM5NzIxMy03OTI1LTQ4MjktYTljMi0yODFhODdjZWJjMTJcL3VzZXJzXC9od2Vla3MiLCJzY3AiOiJtZW1iZXItb2YtZ3JvdXBzOiogYXBpOioiLCJhdWQiOiJqZi1hcnRpZmFjdG9yeUAyZWM5NzIxMy03OTI1LTQ4MjktYTljMi0yODFhODdjZWJjMTIiLCJpc3MiOiJqZi1hcnRpZmFjdG9yeUAyZWM5NzIxMy03OTI1LTQ4MjktYTljMi0yODFhODdjZWJjMTJcL3VzZXJzXC9od2Vla3MiLCJpYXQiOjE2MTY1MDY5ODUsImp0aSI6IjhmNDIxYTY2LTlkMjMtNDkyOS1hYjFhLWJlZDA3N2YzZmNiOSJ9.bxNnGx0I6_QDx-9d1xzKgF9jcF879o5pk5AnuxOG6RmeB4fAbA_-g1NJDGEi_qtXfW--AAfOLUu4rskzAy3rv9_GfzXS0wnA6pPrEwh2JT-Jo6UD8olcu1ICca2pPo-Q63Y1Sc-XvmZBZOqFCYizheBtEs-EZDK1O6ifsNleLMnHUPktc5dd_ehgD_J_yxeFoeqDIVqRmSWCMy_HyPVG6_bw5TaaesjUKzttRhGAmjeahXCFhIJqTlebHbpja9ZEONMx1g_hyRB51BYWUCmJNr5jdT_wgIzEsjkVGWtqzzJ4Lc5MgisXUSx2B1bXJxBsWkHhJ64vcNs2JaKlU-LLGg


npmScopes:
  quarry:
    npmAlwaysAuth: false
    npmRegistryServer: "https://artifactory.corp.adobe.com/artifactory/api/npm/npm-adobe-release/"
  react:
    npmPublishRegistry: "https://artifactory.corp.adobe.com/artifactory/api/npm/npm-react-release/"
    npmRegistryServer: "https://artifactory.corp.adobe.com/artifactory/api/npm/npm-react-release/"

packageExtensions:
  "@adobe/react-spectrum@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@quarry/header@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
      react-intl: "*"
  "@quarry/inventory@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
  "@react-aria/numberfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-aria/select@*":
    peerDependencies:
      react-dom: "*"
  "@react-aria/spinbutton@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/actiongroup@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/breadcrumbs@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/button@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/buttongroup@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/checkbox@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/dialog@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/label@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/listbox@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/menu@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/numberfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/picker@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/provider@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/radio@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/searchfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/switch@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/table@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/tabs@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/textfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/theme-dark@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@react-spectrum/theme-default@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@react-spectrum/theme-light@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@react-spectrum/tooltip@*":
    peerDependencies:
      react-dom: "*"
  "sandbox@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
  "@spectrum-icons/illustrations@*":
    peerDependencies:
      react-dom: "*"
  "@spectrum-icons/ui@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
      react-dom: "*"
  "@spectrum-icons/workflow@*":
    peerDependencies:
      "@react-spectrum/provider": "*"
      react-dom: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.4.2.cjs
