yarnPath: ".yarn/releases/yarn-berry.cjs"

packageExtensions:
  "@react-spectrum/contextualhelp@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/button@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/buttongroup@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/checkbox@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/label@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/radio@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/searchfield@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/switch@*":
    peerDependencies:
      react-dom: "*"
  "@react-spectrum/textfield@*":
    peerDependencies:
      react-dom: "*"
  "@spectrum-icons/ui@*":
    peerDependencies:
      react-dom: "*"
  "@spectrum-icons/workflow@*":
    peerDependencies:
      react-dom: "*"